### ISSUE TITLE
Crash after Update

### ISSUE THREAD

**Issue by stemeda** [digedag/rn_base#149]
`Fatal error: Interface 'Sys25\RnBase\Frontend\Request\ParametersInterface' not found in .../typo3conf/ext/rn_base/class.tx_rnbase_parameters.php on line 34 `
PHP 7.2
Typo3 8.7.27

**Comment by digedag** [comment]
I suppose the system is running without composer? Did you try to refresh class map?
```
typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation
```
From which version did you update?

**Comment by stemeda** [comment]
Yes correct I do not use composer.

`> typo3/cli_dispatch.phpsh extbase extension:dumpclassloadinginformation
Status: 500 Internal Server Error`
 I'm allways updating directly from github using the script https://github.com/digedag/cfc_league_fe/commit/d2e693e31d7f9a4c3752c2e6f3e65872dfb43ca4#diff-04c6e90faac2675aa89e2176d2eec7d8

The latest Changelog starts with
```
Changelog
---------

v1.9.2 (??.??.2019)

v1.9.1 (22.01.2019)
 * doQuery in DatabaseConnection fixed #132```

**Comment by digedag** [comment]
You should try to find out, why `dumpclassloadinginformation` fails. You need to reload class loading information. This is not done automatically if you update extension from git repos. That's why using composer is a good idea!
Another way would be to uninstall and reinstall rn_base. But that's a mess since there are many dependend extensions...

**Comment by stemeda** [comment]
Yes, you are right. But currently no time to migrate the project to composer.

I've not uninstalled rn_base, cfc_league and cfc_league_fe, made the update an installed again. Afterwards everything works fine.

Thanks for help!
